### model
model_name_or_path: ${QWEN3_OMNI_MODEL}
trust_remote_code: true
quantization_bit: 4
quantization_method: bnb

### method
stage: sft
do_train: true
do_eval: false
finetuning_type: lora
lora_rank: 4
lora_alpha: 8
lora_dropout: 0.05
lora_target: q_proj,v_proj
flash_attn: auto
freeze_vision_tower: true
freeze_multi_modal_projector: true
print_param_status: false
upcast_layernorm: true

### dataset
dataset: dcase_adqa_qwen3_final_train_dev_strong_empty5
dataset_dir: ${FUN_AUDIO_CHAT_ROOT}/training/data
template: qwen3_omni_nothink
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 4
dataloader_num_workers: 2

### output
output_dir: ${OUTPUT_ROOT}/qwen3_omni_lora
logging_steps: 10
save_strategy: steps
save_steps: 1000
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
learning_rate: 5.0e-5
max_steps: 2000
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
disable_gradient_checkpointing: false
